apiVersion: v1
kind: Service
metadata:
  name: {{ include "rails-app.fullname" . }}
  labels:
    {{- include "rails-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  # I have set both ports to 3000
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "rails-app.selectorLabels" . | nindent 4 }}
  